# Generated by Django 5.0 on 2023-12-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('orientation', models.CharField(choices=[('forward', 'forward'), ('reverse', 'reverse')], max_length=100)),
                ('sequence', models.CharField(max_length=100)),
                ('taille', models.IntegerField()),
                ('pourcentage_gc', models.FloatField()),
                ('temperature_melting', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille_fragment', models.IntegerField()),
                ('programme_pcr', models.CharField(max_length=10000)),
                ('region', models.CharField(max_length=100)),
                ('bibliographie', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('amorce_forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amorce_forward', to='db_explorer.amorce')),
                ('amorce_reverse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amorce_reverse', to='db_explorer.amorce')),
            ],
        ),
    ]
