# Generated by Django 5.0 on 2023-12-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_interne', models.CharField(max_length=100)),
                ('code_client', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_reception', models.DateField()),
                ('date_rendu', models.DateField()),
                ('date_suppression', models.DateField()),
                ('type_barcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Librairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_librairie', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Couple_Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_explorer.couple')),
                ('id_echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_explorer.echantillon')),
            ],
        ),
        migrations.CreateModel(
            name='Librairie_Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_explorer.echantillon')),
                ('id_librairie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_explorer.librairie')),
            ],
        ),
    ]
